import { Inter } from "@next/font/google";
import "@/styles/globals.scss";
import type { AppProps } from "next/app";
// Redux 관련
import { Provider } from "react-redux";
import { store } from "@/store";
import { PersistGate } from "redux-persist/integration/react";
import { persistStore } from "redux-persist";
// Header, Footer
import Head from "next/head";
import Footer from "@/components/footer";
import Header from "@/components/header";

const inter = Inter({ subsets: ["latin"] });

let persistor = persistStore(store);

const App = ({ Component, pageProps }: AppProps) => {
  return (
    <>
      <Head>
        <title>Plateer Mall</title>
        <meta name="description" content="Plateer FO generated by NEXT.js 13" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <Header />
          <Component {...pageProps} />
          <Footer />
        </PersistGate>
      </Provider>
    </>
  );
};

export default App;
